name: Daily README Update with GitHub Stats

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # This schedules the workflow to run daily at midnight

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Ensure using v3

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh -y

      - name: Authenticate with GitHub CLI
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo $GH_PAT | gh auth login --with-token

      - name: Generate GitHub Stats
        env:
          GH_README_STATS_TOKEN: ${{ secrets.GH_README_STATS_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_README_STATS_TOKEN" -o README.md \
          "https://github-readme-stats.vercel.app/api?username=hanaeddoud-poc&show_icons=true&theme=aura&count_private=true"

      - name: Commit and push if changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with latest stats' || echo "No changes to commit"
          gh auth status
          git push

